/*
 * Copyright 2013 MovingBlocks
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.terasology.cities.testing;

/**
 * A temporary list for fantasy town names used in the Swing Debug Renderer
 * @author Martin Steiger
 */
public final class NameList {

    /**
     * A list of fantasy town names
     */
    public static final String[] NAMES = { 
        "Belcoast",
        "Appleville",
        "Bluebeach Downs",
        "Zurgonipal",
        "Brookmoor",
        "Khuul",
        "Butterice",
        "Ashalmawia",
        "Courtmarsh",
        "Velothi",
        "Crystalshadow",
        "Kohgoruhn",
        "Crystalwyn Island",
        "Urshilaku",
        "Deepmoor Barrens",
        "Valenvelvar",
        "Edgegate",
        "Dagonfel",
        "Eribank",
        "Mora",
        "Estercoast",
        "Sandrith",
        "Fairburn Point",
        "Assarinibib",
        "Freywall",
        "Erabenimsun",
        "Highdale",
        "Holamayn",
        "Highmeadow",
        "Branora",
        "Ironville Crossing",
        "Telasero",
        "Jancastle",
        "Ebonheart",
        "Janlyn",
        "Ald Sotha",
        "Landpond",
        "Vivec",
        "Linland",
        "Seyda",
        "Linmeadow",
        "Odar",
        "Lochhurst",
        "Uvirith",
        "Lorbeach",
        "Falensarano",
        "Mageland",
        "Zaina",
        "Mallowcoast",
        "Nuchuleft",
        "Maplebarrow",
        "Moonmoth",
        "Mapleport",
        "Balmora",
        "Marbleton",
        "Hlormaren",
        "Marblewolf Shore",
        "Gnarr",
        "Meadowlake",
        "Khartag",
        "Newlake Island",
        "Andrasreth",
        "Newviolet Pond",
        "Ginisis",
        "Prymarsh",
        "Berandes",
        "Riverlake",
        "Koal",
        "Roseglass",
        "Bul Isra",
        "Rosewall",
        "Marr Gan",
        "Shadowmoor Downs",
        "Vemynal",
        "Silverbutter Shore",
        "Tureynulal",
        "Southfalcon",
        "Volmoria",
        "Starryoak Barrow",
        "Suron",
        "Stoneby",
        "Suran",
        "Strongby",
        "Odrosal",
        "Swynborough",
        "Caldera",
        "Westertown",
        "Ald Ruhn",
        "Wildebush",
        "Buckmoth",
        "Winterbarrow",
        "Wintercliff",
        "Wolfkeed",
        "Woodbush",
        "Aldcliff",
        "Aldmead",
        "Barrowwald",
        "Bayfield",
        "Clifflake",
        "Coldshadow",
        "Deepcrest",
        "Deephall Point",
        "Deepspell Lake",
        "Dellgate",
        "Dorhaven",
        "Dragonmarsh",
        "Fallash Bridge",
        "Fallville",
        "Fayfair",
        "Glasscliff",
        "Glasscliff",
        "Greendell Barrens",
        "Greymarsh",
        "Icebarrow",
        "Lintown",
        "Mallowbrook Hedge",
        "Maplehurst",
        "Merribourne",
        "Norbank",
        "Northhollow",
        "Oldcastle",
        "Oldton Island",
        "Orness",
        "Orwald",
        "Prywyn",
        "Redcliff",
        "Riverton",
        "Seamarsh",
        "Shadowdale",
        "Shadowpond Point",
        "Summermarsh",
        "Valacre",
        "Valwick",
        "Vertmount Downs",
        "Watercoast",
        "Wellbeach Field",
        "Westbay",
        "Westervale",
        "Wheatland",
        "Whiteedge",
        "Whitehollow",
        "Whitepine",
        "Wildefort",
        "Winterfall Mill",
        "Aelwynne",
        "Aldmaple",
        "Ashbush",
        "Bluebeach",
        "Butterborough Point",
        "Clearham Downs",
        "Clifffield",
        "Coldrose",
        "Coldshore",
        "Easthaven",
        "Fairmeadow",
        "Falconlake",
        "Fallhedge",
        "Faycastle",
        "Goldlyn",
        "Greendell",
        "Greywater Edge",
        "Icefay",
        "Lochfort",
        "Marbledragon",
        "Marblemoor",
        "Marblepond",
        "Marbleport",
        "Morcrest",
        "Oakborough",
        "Oldshade",
        "Raypond",
        "Riveredge",
        "Riverhaven",
        "Rosesage Bush",
        "Seafort",
        "Silverpond Crags",
        "Snowland",
        "Springfield",
        "Starrycastle",
        "Starrycastle",
        "Stonecliff Forest",
        "Strongwheat Cliff",
        "Summerby",
        "Summergrass",
        "Swynfield",
        "Vertloch Bridge",
        "Westercoast",
        "Westiron Coast",
        "Whitewell Land",
        "Winterland",
        "Wintermead",
        "Winterness",
        "Witchlyn",
        "Woodbush Crossing"
    };
    
    
    private NameList() {
    }

}
