on: [push]
  
  name: Build and publish assets
  
  jobs:
    build:
      name: Build and upload release assets
      runs-on: ubuntu-latest      
      steps:
        - id: terasology
          name: Get Latest Engine Release
          uses: pozetroninc/github-action-get-latest-release@v0.3.0
          with:
            repository: MovingBlocks/Terasology
        - name: Checkout Engine
          uses: actions/checkout@v2
          with:
            repository: MovingBlocks/Terasology
            ref: ${{ steps.terasology.outputs.release }}
        - name: Checkout Module
          uses: actions/checkout@v2
          with:
            path: modules/${{ github.event.repository.name }}
        - name: Set up JDK 8
          uses: actions/setup-java@v1
          with:
            java-version: 8
        - name: Get module version
          run: echo '::set-env name=MODULE_VERSION::$(./gradlew :modules:${{ github.event.repository.name }}:properties | grep "version:" | awk "{print $2}")'
          shell: bash
        - name: Build module JAR
          run: ./gradlew :modules:${{ github.event.repository.name }}:jar
        - name: Upload Build Artifact
          uses: actions/upload-artifact@v2
          with:
            name: ${{ github.event.repository.name }}-$MODULE_VERSION.jar
            path: modules/${{ github.event.repository.name }}/build/libs/${{ github.event.repository.name }}-$MODULE_VERSION.jar
  